### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by motkeg** [motkeg/social-ware#1]
## Task list for `main page`
- [ ] clean and fix the text.
- [ ] decorate the page.
- [ ] read the project from the database and embedded them into the contact.
- [ ] decorate the "project model" that contain information about each project.
- [ ]  fix "contact me" to be work.
