### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by motkeg** [motkeg/social-ware#2]
## Tasks for `dashboard.html`
- [ ]  _**find way to get developer information from GitHub (user name,repo etc), figure how using gh3 can help**_
- [ ] decorate all linked pages.
- [ ] decorate the main content of dashboard.
- [ ] read data from the  database about the user and embedded it.
- [ ] retrieve data to links : tasks bar,notification
