### ISSUE TITLE
Projects page

### ISSUE THREAD

**Issue by motkeg** [motkeg/social-ware#4]
## Tasks to `project.html` and `new-project.html`
- [ ] decorate pages.
- [ ] create Templete to  `<td>` that embedded into table page
- [ ] retrieve the data from the database and embedded it.
- [ ] impemente the functionalty for evrey project: (edit,view...etc)
### new project
- [ ] decide the steps for a new project and fix the content.
- [ ]  write project details to database.
